Valgrind, google, options
kayofeld/script-installation-ordinateur-epitech pull request #12
Opened 2017-08-07 13:17 UTC by extragornax

Bonjour !

Petite PR sympa.
J'ai ajouté colour-valgrind, très utile pour ceux qui utilisent valgrind souvent.
Correction et ajout sur le man google
Mise en options de FZ, tree et terminator

Merci,

2017-08-07 14:14 UTC, bew commented on installation/install
> +sys_install python-pip
Ce serai pas plutôt `python3-pip` ?

2017-08-07 14:19 UTC, extragornax commented on installation/install
> +sys_install python-pip
Si ^^

2017-08-14 16:20 UTC, kayofeld requested changes
Incohérence entre README.md et install

2017-08-14 16:20 UTC, kayofeld commented on README.md
> +    - tree
Tree et filezilla ne sont pas optionnels
En effet filezilla devrait l'être

2017-08-17 12:25 UTC, extragornax commented on README.md
> +    - tree
Updated

2017-08-26 11:06 UTC, extragornax commented
Updated

2017-08-27 14:58 UTC, kayofeld commented on installation/install
> +read -p "Installer makefile-gen pour générer vos makefiles ? [O/n]" yn
It's not makefile-gen that is installed.
Why put tree and filezilla in the same package ? it's not the same usage and is therefore pointless.
+ I don't want tree to be an optionnal package on this script for now

2017-08-27 15:02 UTC, kayofeld commented on installation/.files/google.1
> +\fBPlus:\fR
Adding the plus is a good idea !
And thanks for correcting the typo.
BUT: I've put a lot of creativity in creating original content for each example. Reusing "Carmen Electra" is not the best way to put your creative capabilities into this document :)

2017-08-27 15:03 UTC, kayofeld requested changes
Changes are to be made on the google.1 and Readme and install.

2017-08-27 15:04 UTC, kayofeld commented on README.md
> +    - tree
tree ne devrait pas être optionel :x

2017-09-14 10:45 UTC, extragornax commented
Updated

2017-09-17 13:40 UTC, kayofeld commented
Salut,
Merci pour ta contribution, as-tu regardé les commentaires ?
Tree ne fait plus partie du projet ? Le readme l'a toujours en paquet optionnel, le man google a une modif à faire.
Les modules optionnels ne devraient pas se retrouver entre les modules qui ne le sont pas (ici ocaml par exemple)
J'ai fait exprès de pas mettre terminator en optionnel. Les gens n'utilisent tmux qu'en ssh et je veux pousser son utilisation.
Une version plus modulaire arrivera, mais ce sera packagé. Sinon autant tout mettre en optionnel

2017-09-19 13:44 UTC, closed without merging