Added CSFML
kayofeld/script-installation-ordinateur-epitech pull request #21
Opened 2020-04-20 15:42 UTC by 1t3x

Credit for the commands goes to: https://github.com/Mitix-EPI

2020-05-06 23:50 UTC, kayofeld commented
Salut !
Merci pour la pull request :)
Cela dit, la fonction sys_install permet d'installer de façon agnostique au système.
Ainsi, on est pas limité à des systèmes basés Debian
Par ailleurs, je conseille de plutôt utiliser "apt" que "apt-get" 👍

2020-05-13 19:11 UTC, 1t3x commented
Salut,
Parfait j'avais pas vu qu'il y avait une function pour ça, j'ai remplacé les apt-get avec le sys_install

2020-08-16 22:03 UTC, kayofeld requested changes

2020-08-16 22:03 UTC, kayofeld commented on installation/install
> +    git clone https://github.com/SFML/CSFML
duplicate

2020-08-16 22:04 UTC, kayofeld commented on installation/install
> +    git clone https://github.com/SFML/CSFML
Sorry, forgot to publich the change request

2020-09-24 08:58 UTC, 1t3x reviewed
One is CSFML and the other is SFML we need both of them

2020-09-24 08:58 UTC, 1t3x commented on installation/install
> +    git clone https://github.com/SFML/CSFML
One is SFML and the other is CSFML

2025-12-01 15:28 UTC, closed without merging