Added support for Solus
kayofeld/script-installation-ordinateur-epitech pull request #9
Opened 2017-02-17 22:09 UTC by AktasC

I tried different things but this is the best out of it.
I would have loved to integer fish instead of zsh, in my opinion it's more complete ..
Also, I don't think /usr/bin/zsh works since, for me at least, it was always found at /bin/zsh ..
One more thing to note is that we need "sudo" to use "chsh" in Solus.

If you need more details or need me to modify some stuff just ask for it and I'll try to do it right away :)

2017-02-17 22:59 UTC, Bew78LesellB commented
> I would have loved to integer fish instead of zsh, in my opinion it's more complete ..

I don't agree, but you have the right to be wrong :)

I'd say that out-of-the-box fish is prettier, but I don't think it's more powerful.. (can you make a snake game, or a FTP server using only fish (without external programs like curl..) ? In zsh you can !)

> Also, I don't think /usr/bin/zsh works since, for me at least, it was always found at /bin/zsh ..

The final binaries can be in different places, but I don't think it's a reason to disable zsh installation (you could make a condition around `chsh` for solus)

What do you think ?

2017-02-17 23:07 UTC, bew requested changes

2017-02-17 23:07 UTC, bew commented on installation/install
> +sys_install make
as `make` is also used for compilation, you should put his installation in the block named `INSTALLATION DE BUILD-ESSENTIAL POUR COMPILER`

In fact, I would write it like (before the GCC block):
```sh
script_header	"INSTALLATION DES OUTILS POUR LA COMPILATION"
if "$os" != "solus"; then
    sys_install build-essential
fi
sys_install make
```
Feel free to make it like this, or to justify your choices

2017-02-17 23:07 UTC, bew commented on installation/install
> +sys_install g++
You should put the installation of `g++` next the compilation of `gcc` (you can of course rename the block to mention the 2)

2017-02-17 23:07 UTC, bew commented on installation/install
> +fi
the condition against `solus` is only on the package installation, you should have only 1 instruction for the `script_header` and do the condition around the `sys_install` command instead, with a branching like:
```
if ...; then
    # ...
else
    # ...
fi
```

2017-02-17 23:07 UTC, Bew78LesellB commented on installation/install
> +	which zypper &> /dev/null && os="opensuse"
Why did you move opensuse & fedora position ?

Basically, when you make a pull request, you should modify or add lines related with the issue you are resolving

In this case, you should not move/change lines that are not related to `add support for solus`.

2017-02-17 23:07 UTC, Bew78LesellB commented on installation/install
> +			;;
Same comment as above on the movement of lines, not related to you issue

If you want to move or refactor codes, you should open an other issue for that, and we will discuss it

2017-02-17 23:07 UTC, Bew78LesellB commented on installation/install
> +				;;
Same comment on moving lines

2017-02-17 23:07 UTC, Bew78LesellB commented on installation/install
> +fi
So you disable ZSH installation for `solus` ?

2017-02-17 23:07 UTC, Bew78LesellB commented on installation/install
> +echo "alias ne='emacs -nw'" >> /home/$USER/.bashrc
to reduce code duplication, maybe you could populate a `~/.aliases.sh` file with aliases, and source it in `~/.bashrc` & `~/.zshrc`

2017-02-18 13:50 UTC, AktasC commented on installation/install
> +	which zypper &> /dev/null && os="opensuse"
I just changed the positions so that it gets in the alphabetical order.

2017-02-18 13:56 UTC, AktasC commented
Thanks for your review.
I will modify and then push again my job when it's totally done.

As for ZSH : 
I've used it for one year at epitech then I swaped for fish which I found better for auto-completion and other stuff without having to configure anything.
In my opinion, a tool that you have to configure in order to get what you could with another isn't a good tool.
Plug'n'Play is kinda better for me since I'm jumping from one OS to the other every week.
I used to have my Arch Distro on Reddit's UnixPorn section and it pleased a lot of people.
For now, I will focus on improving your script and will certainly also add support for Deepin (since a lot of people use it in my school currently).

2017-02-18 14:04 UTC, AktasC commented
Thanks for your review.
I will modify and then push again my job when it's totally done.

As for ZSH : 
I've used it for one year at epitech then I swaped for fish which I found better for auto-completion and other stuff without having to configure anything.
In my opinion, a tool that you have to configure in order to get what you could with another isn't a good tool.
Plug'n'Play is kinda better for me since I'm jumping from one OS to the other every week.
I used to have my Arch Distro on Reddit's UnixPorn section and it pleased a lot of people.
For now, I will focus on improving your script and will certainly also add support for Deepin (since a lot of people use it in my school currently).

2017-02-18 14:04 UTC, closed without merging

2017-02-18 14:16 UTC, Bew78LesellB commented
Why did you closed this PR ? You can  continue tu push on your branch and the PR here will update accordingly

2017-02-18 14:18 UTC, Bew78LesellB commented on installation/install
> +	which zypper &> /dev/null && os="opensuse"
Oh nice, I understand & like that, let's keep it that way then! 

I think you should have made a commit which mentioned this, so there would be no misunderstanding

2017-02-18 14:30 UTC, Bew78LesellB commented
> In my opinion, a tool that you have to configure in order to get what you could with another isn't a good tool.

I don't agree but I understand your point. 

Deepin..  don't know, but it's great, thank you!

2017-02-18 14:45 UTC, AktasC commented
I closed it because I made another pull request, didn't wanna pollute here..
We both know what Deepin is worth but .. Yeah .. Some people like it.